#pragma once

// utils
#include "utils/BasicList.hpp"
// program
#include "program/Program.hpp"
#include "program/MainClass.hpp"
#include "program/ClassDeclList.hpp"
// statements
#include "statements/Statement.hpp"
#include "statements/AssertStmt.hpp"
#include "statements/LocalVarDeclStmt.hpp"
#include "statements/StmtListStmt.hpp"
#include "statements/ConditionalStmt.hpp"
#include "statements/PrintStmt.hpp"
#include "statements/StmtList.hpp"
#include "statements/AssignmentStmt.hpp"
// expressions
#include "expressions/Expression.hpp"
#include "expressions/BinOpExpr.hpp"
#include "expressions/BoolConstExpr.hpp"
#include "expressions/IntExpr.hpp"
#include "expressions/NewExpr.hpp"
#include "expressions/NotExpr.hpp"
#include "expressions/IdentExpr.hpp"
// declarations
#include "declarations/Decl.hpp"
#include "declarations/VarDecl.hpp"
#include "declarations/ClassDecl.hpp"
#include "declarations/DeclList.hpp"
// value categories
#include "value_categories/Lvalue.hpp"
