#pragma once

#include "types/Type.hpp"

// utils
class BasicList;
// program
class Program;
class MainClass;
class ClassDeclList;
// statements
class Statement;
class AssertStmt;
class LocalVarDeclStmt;
class StmtListStmt;
class IfStmt;
class IfElseStmt;
class WhileStmt;
class PrintStmt;
class AssignmentStmt;
class StmtList;
class ReturnStmt;
class MethodStmt;
// expressions
class Expression;
class BinOpExpr;
class SubscriptExpr;
class LengthExpr;
class TrueExpr;
class FalseExpr;
class IntExpr;
class NewExpr;
class NewArrayExpr;
class NotExpr;
class IdentExpr;
class MethodExpr;
class ThisExpr;
// declarations
class Decl;
class VarDecl;
class MethodDecl;
class ClassDecl;
class DeclList;
// scopes
class Symbol;
class ScopeLayer;
class ScopeLayerTree;
// types
class Object;
class Integer;
class Bool;
class Class;
class Array;
class UninitObject;
class Function;
// value categories
class Lvalue;
// functions
class MethodInvocation;
class CommaExprList;
class Frame;
class FunctionTable;
class FunctionStorage;
// constructor
class Constructor;
class ObjectBuilder;
class IntegerBuilder;
class BoolBuilder;
class ClassBuilder;
